// <auto-generated />
namespace iot4dx.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class PushMessage_Enviado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PushMessage_Enviado));
        
        string IMigrationMetadata.Id
        {
            get { return "201407311826209_PushMessage_Enviado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
